
Neos:
  Imagine:
    driver: Imagick
  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        dbname: neos-impf
        user: root
        password: codeRoot$
        host: 127.0.0.1
